apiVersion: v1
kind: Secret
metadata:
  name: tams-b2-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tams.name" . }}
type: Opaque
data:
  B2_ENDPOINT: {{ .Values.b2.endpoint | b64enc }}
  B2_REGION: {{ .Values.b2.region | b64enc }}
  B2_BUCKET: {{ .Values.b2.bucket | b64enc }}
  B2_ACCESS_KEY_ID: {{ .Values.b2.accessKey | b64enc }}
  B2_SECRET_ACCESS_KEY: {{ .Values.b2.secretKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tams-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tams.name" . }}
type: Opaque
data:
  TAMS_USERNAME: {{ .Values.tams.username | b64enc }}
  TAMS_PASSWORD: {{ .Values.tams.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tams-mongo-credentials
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tams.name" . }}
type: Opaque
data:
  MONGO_URI: {{ .Values.mongoUri | b64enc }}
